#!/usr/bin/env python3
from pathlib import Path
import sys

if len(sys.argv) != 2:
    raise SystemExit(f"usage: {sys.argv[0]} path/to/src/c99.c")

path = Path(sys.argv[1])
src = path.read_text()


def replace_once(label: str, old: str, new: str) -> None:
    global src
    count = src.count(old)
    if count != 1:
        raise SystemExit(f"augment_slice_string: {label}: expected exactly one anchor, found {count}")
    src = src.replace(old, new, 1)


replace_once(
    "len builtin",
    '''static Bool emit_call(C99 *c, const CallExpression *call) {
\tif (call->operand->kind == EXPRESSION_IDENTIFIER) {''',
    '''static Bool emit_call(C99 *c, const CallExpression *call) {
\tif (call->operand->kind == EXPRESSION_IDENTIFIER) {
\t\tconst Identifier *identifier = RCAST(const IdentifierExpression *, call->operand)->identifier;
\t\tif (string_compare(identifier->contents, SCLIT("len"))) {
\t\t\tif (array_size(call->arguments) != 1) return unsupported(c, "len argument count");
\t\t\tconst Expression *argument = call->arguments[0]->value;
\t\t\tCType type = sema_infer_expression(&c->sema, argument);
\t\t\tif (type != CTYPE_SLICE_U8 && type != CTYPE_STRING) {
\t\t\t\treturn unsupported(c, "len operand type");
\t\t\t}
\t\t\tfputc('(', c->out);
\t\t\tif (!emit_expression(c, argument)) return false;
\t\t\tfputs(").len", c->out);
\t\t\treturn true;
\t\t}
\t}

\tif (call->operand->kind == EXPRESSION_IDENTIFIER) {''',
)

replace_once(
    "string literal",
    '''\tcase EXPRESSION_LITERAL:
\t\tfprintf(c->out, "%.*s", SFMT(RCAST(const LiteralExpression *, expression)->value));
\t\treturn true;''',
    '''\tcase EXPRESSION_LITERAL: {
\t\tconst LiteralExpression *literal = RCAST(const LiteralExpression *, expression);
\t\tif (literal->kind == LITERAL_STRING) {
\t\t\tif (!literal->value.length || literal->value.contents[0] != '\"') {
\t\t\t\treturn unsupported(c, "raw/non-C string literal");
\t\t\t}
\t\t\tfputs("(codin_string){ .data = (const uint8_t *)", c->out);
\t\t\tfprintf(c->out, "%.*s", SFMT(literal->value));
\t\t\tfputs(", .len = sizeof(", c->out);
\t\t\tfprintf(c->out, "%.*s", SFMT(literal->value));
\t\t\tfputs(") - 1 }", c->out);
\t\t\treturn true;
\t\t}
\t\tfprintf(c->out, "%.*s", SFMT(literal->value));
\t\treturn true;
\t}''',
)

replace_once(
    "slice/string indexing and slicing",
    '''\tcase EXPRESSION_INDEX: {
\t\tconst IndexExpression *index = RCAST(const IndexExpression *, expression);
\t\tif (index->rhs) return unsupported(c, "multi-index expression");
\t\tif (!emit_expression(c, index->operand)) return false;
\t\tfputc('[', c->out);
\t\tif (!emit_expression(c, index->lhs)) return false;
\t\tfputc(']', c->out);
\t\treturn true;
\t}
\tcase EXPRESSION_COMPOUND_LITERAL:''',
    '''\tcase EXPRESSION_INDEX: {
\t\tconst IndexExpression *index = RCAST(const IndexExpression *, expression);
\t\tif (index->rhs) return unsupported(c, "multi-index expression");
\t\tCType operand_type = sema_infer_expression(&c->sema, index->operand);
\t\tif (operand_type == CTYPE_SLICE_U8 || operand_type == CTYPE_STRING) {
\t\t\tfputc('(', c->out);
\t\t\tif (!emit_expression(c, index->operand)) return false;
\t\t\tfputs(").data[", c->out);
\t\t} else {
\t\t\tif (!emit_expression(c, index->operand)) return false;
\t\t\tfputc('[', c->out);
\t\t}
\t\tif (!emit_expression(c, index->lhs)) return false;
\t\tfputc(']', c->out);
\t\treturn true;
\t}
\tcase EXPRESSION_SLICE: {
\t\tconst SliceExpression *slice = RCAST(const SliceExpression *, expression);
\t\tif (!slice->lhs || !slice->rhs) return unsupported(c, "open-ended slice");
\t\tif (sema_infer_expression(&c->sema, slice->operand) != CTYPE_U8_PTR) {
\t\t\treturn unsupported(c, "slice operand type");
\t\t}
\t\tfputs("(codin_slice_u8){ .data = &", c->out);
\t\tif (!emit_expression(c, slice->operand)) return false;
\t\tfputc('[', c->out);
\t\tif (!emit_expression(c, slice->lhs)) return false;
\t\tfputs("], .len = (uintptr_t)(", c->out);
\t\tif (!emit_expression(c, slice->rhs)) return false;
\t\tfputs(" - ", c->out);
\t\tif (!emit_expression(c, slice->lhs)) return false;
\t\tfputs(") }", c->out);
\t\treturn true;
\t}
\tcase EXPRESSION_COMPOUND_LITERAL:''',
)

replace_once(
    "u8 fixed array semantic handle",
    '''\t\t\tif (!sema_add_local(&c->sema, declaration->names[0]->contents, CTYPE_UNKNOWN)) {
\t\t\t\treturn unsupported(c, "local symbol capacity");
\t\t\t}
\t\t\treturn true;''',
    '''\t\t\tCType array_sem_type = sema_type_from_ast(array->type) == CTYPE_U8
\t\t\t                     ? CTYPE_U8_PTR : CTYPE_UNKNOWN;
\t\t\tif (!sema_add_local(&c->sema, declaration->names[0]->contents, array_sem_type)) {
\t\t\t\treturn unsupported(c, "local symbol capacity");
\t\t\t}
\t\t\treturn true;''',
)

replace_once(
    "zero-code runtime value types",
    '''\tfputs("/* generated by Codin's strict C99 backend */\\n"
\t      "#include <stdbool.h>\\n"
\t      "#include <stddef.h>\\n"
\t      "#include <stdint.h>\\n\\n", out);''',
    '''\tfputs("/* generated by Codin's strict C99 backend */\\n"
\t      "#include <stdbool.h>\\n"
\t      "#include <stddef.h>\\n"
\t      "#include <stdint.h>\\n\\n"
\t      "typedef struct { uint8_t *data; uintptr_t len; } codin_slice_u8;\\n"
\t      "typedef struct { const uint8_t *data; uintptr_t len; } codin_string;\\n\\n", out);''',
)

replace_once(
    "static string constant initializer",
    '''\t\t\t\tconst char *type_name = sema_c_type_name(type);
\t\t\t\tif (!type_name) return unsupported(c, "top-level constant type");
\t\t\t\tfprintf(c->out, "static const %s %.*s = ", type_name, SFMT(name->contents));
\t\t\t\tif (!emit_expression(c, value)) return false;
\t\t\t\tfputs(";\\n", c->out);''',
    '''\t\t\t\tconst char *type_name = sema_c_type_name(type);
\t\t\t\tif (!type_name) return unsupported(c, "top-level constant type");
\t\t\t\tfprintf(c->out, "static const %s %.*s = ", type_name, SFMT(name->contents));
\t\t\t\tif (type == CTYPE_STRING && value->kind == EXPRESSION_LITERAL) {
\t\t\t\t\tconst LiteralExpression *literal = RCAST(const LiteralExpression *, value);
\t\t\t\t\tif (literal->kind != LITERAL_STRING || !literal->value.length ||
\t\t\t\t\t    literal->value.contents[0] != '\"') {
\t\t\t\t\t\treturn unsupported(c, "static string literal");
\t\t\t\t\t}
\t\t\t\t\tfputs("{ .data = (const uint8_t *)", c->out);
\t\t\t\t\tfprintf(c->out, "%.*s", SFMT(literal->value));
\t\t\t\t\tfputs(", .len = sizeof(", c->out);
\t\t\t\t\tfprintf(c->out, "%.*s", SFMT(literal->value));
\t\t\t\t\tfputs(") - 1 }", c->out);
\t\t\t\t} else if (!emit_expression(c, value)) {
\t\t\t\t\treturn false;
\t\t\t\t}
\t\t\t\tfputs(";\\n", c->out);''',
)

path.write_text(src)
print("augment_slice_string: []u8 + string value lowering applied")
